# Generated by Django 4.2.3 on 2023-11-13 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energydisplayer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='energydisplayer',
            name='displayerType',
            field=models.CharField(choices=[('energy', 'energy'), ('consommation', 'consommation')], default=('energy', 'energy'), max_length=50, verbose_name='Select your enegy type'),
        ),
        migrations.AddField(
            model_name='energydisplayer',
            name='energyCo2Factor',
            field=models.FloatField(blank=True, null=True, verbose_name='Indicate co2 factor about your energy (default -> gaz: 0.443, electricity: 0.068)'),
        ),
        migrations.AddField(
            model_name='energydisplayer',
            name='isVisible',
            field=models.BooleanField(default=True, verbose_name='Visible ?'),
        ),
        migrations.AddField(
            model_name='energydisplayer',
            name='showPedagogicCommation',
            field=models.BooleanField(default=False, verbose_name='Show pedagogic consommation display'),
        ),
        migrations.AddField(
            model_name='energydisplayer',
            name='energyType',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='energydisplayer.energytype', verbose_name='Choice your energy type variable related'),
        ),
    ]
