# Generated by Django 4.2.3 on 2023-11-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energydisplayer', '0002_energytype_energydisplayer_displayertype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energydisplayer',
            name='energyCo2Factor',
        ),
        migrations.AddField(
            model_name='energytype',
            name='GESCoeffienciant',
            field=models.FloatField(blank=True, null=True, verbose_name='Indicate co2 factor about your energy (default -> gaz: 0.443, electricity: 0.068)'),
        ),
    ]
