# Generated by Django 4.2.3 on 2023-11-13 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energydisplayer', '0003_remove_energydisplayer_energyco2factor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='energydisplayer',
            old_name='showPedagogicCommation',
            new_name='showPedagogicConsommation',
        ),
    ]
