# Generated by Django 4.2.3 on 2023-11-13 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energydisplayer', '0004_rename_showpedagogiccommation_energydisplayer_showpedagogicconsommation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energydisplayer',
            name='displayerType',
        ),
    ]
